"""Add docs_url and verified to Property

Revision ID: 04bce93c63ea
Revises: c0375a366c36
Create Date: 2025-09-04 09:03:28.051976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04bce93c63ea'
down_revision = 'c0375a366c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docs_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('verified')
        batch_op.drop_column('docs_url')

    # ### end Alembic commands ###
