"""add password_hash to user

Revision ID: 672ba146cf2a
Revises: 48f227bbcf53
Create Date: 2025-09-03 14:45:27.863038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672ba146cf2a'
down_revision = '48f227bbcf53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
